# Generated by Django 2.1.7 on 2019-03-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20190327_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='name',
            new_name='username',
        ),
    ]
